SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE rates ADD COLUMN student_id BIGINT NOT NULL;
ALTER TABLE rates ADD CONSTRAINT fk_rates_user_id FOREIGN KEY (student_id) REFERENCES users(id);
SET FOREIGN_KEY_CHECKS=1;